name: Trigger builds on pull requests to main

on:
  pull_request:
    branches: [main]

jobs:
  build-pull-request-flavors:
    strategy:
      fail-fast: false
      matrix:
        base_flavor: [nvidia, cpu, amd]
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-flavor.yml
    with:
      forge_neo_ref: "neo"
      image_label: "neo"
      base_flavor: ${{ matrix.base_flavor }}
      targets: default
      push_images: false
    secrets: inherit

